##
#https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.1/html-single/Configuring_and_Running_Red_Hat_JBoss_Fuse/#ESBAdminService
##
- name: Create JBoss Fuse Group
  group:
    name: "{{ jboss_fuse_group }}"
    system: yes
    state: present
    gid: "400"
  tags:
    - jboss_fuse

- name: Create JBoss Fuse User
  user:
    name: "{{ jboss_fuse_user }}"
    comment: "JBoss Fuse User"
    uid: "400"
    group: "{{ jboss_fuse_group }}"
    home: "{{ jboss_fuse_library_dest }}"
    shell: "/bin/bash"
  tags:
    - jboss_fuse

- name: Create JBoss Fuse Library Destination
  become: true
  file:
    path: "{{ jboss_fuse_library_dest }}"
    owner: "{{ jboss_fuse_user }}"
    group: "{{ jboss_fuse_group }}"
    state: directory
    mode: "755"
  tags:
    - jboss_fuse

## WIP Adding Fuse as Service, for now its starts the fuse daemon on all nodes
## 

- name: Verify jboss-fuse is running
  wait_for: 
    port: "{{jboss_fuse_ssh_port}}" 
    host: "{{ ansible_ssh_host }}" 
    state: started 
    timeout: 3
  ignore_errors: true
  register: fuse_run_state
  tags: jboss_fuse

##
# Since fuse daemon starts in background its essential to make 
# fuse command run with aysync mode to prevent killing by Ansible
# ref: http://docs.ansible.com/ansible/playbooks_async.html
##
- name: Start Fuse
  become_user: "{{jboss_fuse_user}}"
  command: "{{jboss_fuse_home}}/bin/start"
  async: 30
  poll: 5
  register: fuse_start_state
  when: (fuse_run_state.failed is defined ) and ( fuse_run_state.failed == true)
  tags: jboss_fuse